version: "3"

services:
  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3005:3005"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
      - /frontend/.next
    depends_on:
      - backend
